import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "./components/Header";
import Hero from "./components/Hero";
import Cards from "./components/Cards";
import Install from "./components/Install";
import TestHeader from "./components/TestHeader";

export default function Home() {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>SvelteReplica2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <TestHeader />
      <Hero />
      <Cards />
      <Install />
    </div>
  );
}
