import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "./components/Hero";
import Cards from "./components/Cards";
import Install from "./components/Install";
import TestHeader from "./components/TestHeader";

export default function Home() {
  return (
    <div className="overflow-hidden">
      <Head>
        <title>SvelteReplica2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="z-10 fixed top-0 left-0 right-0 bg-white">
        <TestHeader />
      </div>

      <div className="z-50">
        <Hero />
      </div>

      <div className="z-20">
        <Cards />
      </div>

      <Install />
    </div>
  );
}
